name: Python CI with Makefile

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.17

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          make install

      - name: Run linter
        run: |
          source venv/bin/activate
          make lint

      - name: Run tests
        run: |
          source venv/bin/activate
          make test
